In [3]:
# read csv file
import csv
import pandas as pd
import numpy as np


# Specify the path to your CSV file
csv_file_path = '../datasets/social_media_usage_and_mental_health.csv'

df = pd.read_csv(csv_file_path)

In [4]:
# Convert 'Timestamp' column to pandas datetime format
df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='%m/%d/%Y %H:%M:%S')

# Create 'Date' and 'Time' columns
df['Date'] = df['Timestamp'].dt.date
df['Time'] = df['Timestamp'].dt.time

# Display the resulting DataFrame
#print(df)

# Save to a new file
#df.to_csv('./datasets/modified_dataset.csv', index=False)

In [5]:
# Identify and remove entire duplicate rows
df.drop_duplicates()

# Display the resulting DataFrame without duplicates
#print(df)

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,"13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?",Date,Time
0,2022-04-18 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,3,2,5,4,5,2022-04-18,19:18:47
1,2022-04-18 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,5,4,5,1,1,5,4,5,2022-04-18,19:19:28
2,2022-04-18 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,5,4,3,3,1,4,2,5,2022-04-18,19:25:59
3,2022-04-18 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,5,3,5,1,2,4,3,2,2022-04-18,19:29:43
4,2022-04-18 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,5,5,3,3,3,4,4,1,2022-04-18,19:33:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,2022-05-21 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,3,4,4,2,4,3,4,4,2022-05-21,23:38:28
477,2022-05-22 00:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,...,4,4,4,2,4,4,4,1,2022-05-22,00:01:05
478,2022-05-22 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,...,2,3,3,3,4,2,2,2,2022-05-22,10:29:21
479,2022-07-14 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,...,3,2,2,3,4,4,5,4,2022-07-14,19:33:47
480,2022-11-12 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,...,1,1,3,3,2,2,2,3,2022-11-12,13:16:50

In [6]:
# By Hoda and Raghad

# Replace values in the "Gender" column
valid_genders = ['Male', 'Female']
df['2. Gender'] = np.where(df['2. Gender'].isin(valid_genders), df['2. Gender'], 'Other')


# Save to a new file
#df.to_csv('./datasets/modified_dataset.csv', index=False)